dywee_user_table:
    path:     /admin6833/users/table/{role}
    defaults: { _controller: DyweeUserBundle:User:table, role: user }
    requirements:
        role: user|admin

dywee_admin_homepage:
    path:     /admin6833/{websiteId}
    defaults: { _controller: DyweeUserBundle:User:adminHomePage, websiteId: null }
    requirements:
        websiteId: \d*

dywee_admin_homepage_alias:
    path:     /admin6833/
    defaults: { _controller: DyweeUserBundle:User:adminHomePage }

dywee_user_homepage:
    path:     /admin
    defaults: { _controller: DyweeUserBundle:User:homePage }

dywee_user_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: DyweeUserBundle:User:dashboard }

dywee_admin_user_edit:
    path:     /admin6833/user/{id}/edit
    defaults: { _controller: DyweeUserBundle:UserAdmin:edit }
    requirements:
        id: \d*