<?php

namespace Dywee\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function countActiveUser()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('count(u)')
            ->where('u.enabled = 1');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
